// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuhQNCUauGT2DF9IRVhf_C2Skg-u3Gxf8',
    appId: '1:468846415215:web:b2106b123ae62c573dac9a',
    messagingSenderId: '468846415215',
    projectId: 'anit-unkown-project',
    authDomain: 'anit-unkown-project.firebaseapp.com',
    storageBucket: 'anit-unkown-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIv-Ka7H-HRhBA5xutq8hQSJvm6crxf5g',
    appId: '1:468846415215:android:e1566e261657b7d43dac9a',
    messagingSenderId: '468846415215',
    projectId: 'anit-unkown-project',
    storageBucket: 'anit-unkown-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3p9ZCwpUqBsvOxploSHAAqL_2IGKYwqw',
    appId: '1:468846415215:ios:af33eccd7aa2e5603dac9a',
    messagingSenderId: '468846415215',
    projectId: 'anit-unkown-project',
    storageBucket: 'anit-unkown-project.appspot.com',
    iosClientId: '468846415215-j4fglepod4l34rh08gt5uqpsuf0ifck6.apps.googleusercontent.com',
    iosBundleId: 'com.anti-unkown.',
  );
}
